all:
	g++ -O2 -o nsat -std=c++11 main.cpp sat/solver/NS.cpp sat/solver/ClauseDB.cpp sat/solver/WatchList.cpp sat/solver/selection/Random.cpp sat/solver/selection/Sequential.cpp sat/solver/selection/VSIDS.cpp 3rd/fmt/format.cc
